steps:

- id: Download service account key
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  args:
  - -c
  - gcloud secrets versions access latest --secret=tracking > auth/key.json

- id: Build validation API container image
  name: gcr.io/cloud-builders/docker
  args:
  - build
  - -f
  - validation/Dockerfile
  - -t
  - gcr.io/$PROJECT_ID/${_IMAGE_NAME_}:$BUILD_ID
  - '.'

- id: Push image to registry
  name: gcr.io/cloud-builders/docker
  args:
  - push
  - gcr.io/$PROJECT_ID/${_IMAGE_NAME_}:$BUILD_ID

- id: Deploy Cloud Run
  name: gcr.io/cloud-builders/gcloud
  args:
  - run
  - deploy
  - ${_RUN_NAME_}
  - --image
  - gcr.io/$PROJECT_ID/${_IMAGE_NAME_}:$BUILD_ID
  - --region
  - ${_REGION_}
  - --platform
  - managed
  - --concurrency
  - '20'
  - --port
  - default
  - --max-instances
  - '5' # Need to limit the number of max instances so that it doesn't overwhelm BigQuery
  - --memory
  - 2Gi
  - --cpu
  - '1'
  - --clear-env-vars
  - --no-allow-unauthenticated

timeout: 600s

images:
- 'gcr.io/${PROJECT_ID}/${_IMAGE_NAME_}:$BUILD_ID'

substitutions:
  _IMAGE_NAME_: tracking-validation
  _REGION_: asia-east1
  _RUN_NAME_: tracking-validation
