# Infrastructure parameters
project:
  id: peskas
service_account:
  name: tracking
  description: Tracking data pipeline domain
  display_name: Tracking domain
  role:
    storage:
      name: objectAdmin
    bigquery:
      name: roles/bigquery.user
secret:
  file: auth/key.json
  name: tracking
storage:
  bucket:
    name: peskas-tracking
    location: ASIA
    uniform_access: on
    class: Standard
ingestion:
  daily_update:
    config: cloudbuild_ingestion.yaml
    image:
      name: tracking-ingestion
  scheduler:
    message:
      body: {"branchName": "main"}
  datasets:
    -
      object_prefix: pelagic-data-daily
      object_extension: csv
      overwrite: false
      start_date: "2018-02-08"
      api:
        secret: auth/pelagic.yaml
  continuous_development:
    trigger:
      name: tracking-ingestion
      description: Ingest daily tracking data
      build_config: cloudbuild_ingestion.yaml
      files:
        included: ingestion/**,cloudbuild_ingestion.yaml,params.yaml
      repo:
        name: tracking
        owner: peskas-platform
      branch_pattern: ^main$
aggregation:
  config: cloudbuild_aggregation.yaml
  api:
    image:
      name: tracking-aggregation
    service:
      name: tracking-aggregation
      region: asia-east1
  pubsub:
    topic:
      name: tracking-aggregation
    notification:
      format: json
      event: OBJECT_FINALIZE
    subscription:
      name: tracking-aggregation
      acknowledgement:
        deadline: 600
      retry:
        delay:
          min: 60s
          max: 600s
  continuous_development:
    trigger:
      name: tracking-aggregation
      description: Aggregate tracking data
      build_config: cloudbuild_aggregation.yaml
      files:
        included: aggregation/**,cloudbuild_aggregation.yaml,params.yaml
      repo:
        name: tracking
        owner: peskas-platform
      branch_pattern: ^main$
  endpoint: tracking-aggregation
  bigquery:
    raw:
      dataset: tracking
      location: asia-east1
      table: tracking_raw
      col_types: Tdddddddccdc
      nskip: 1
      write_disposition: WRITE_APPEND
      create_disposition: CREATE_IF_NEEDED
