# Infrastructure parameters
project:
  id: peskas
service_account:
  name: tracking
  description: Tracking data pipeline domain
  display_name: Tracking domain
  role:
    storage:
      name: roles/storage.admin
      condition:
        expression: resource.name=="projects/_/buckets/peskas-tracking"
        title: bucket_is_peskas_tracking
        description: Only grant access to peskas tracking bucket
secret:
  file: auth/key.json
  name: tracking
storage:
  bucket:
    name: peskas-tracking
    location: ASIA
    uniform_access: on
    class: Standard
